// src/components/Button.svelte
<script lang="ts">
  import { swalSlide } from '@swal/ui/motion';

  export let variant: 'primary' | 'secondary' | 'ghost' | 'danger' = 'primary';
  export let size: 'sm' | 'md' | 'lg' = 'md';
  export let disabled = false;
  export let loading = false;
  export let fullWidth = false;

  const base = 'inline-flex items-center justify-center font-medium transition-all duration-150 will-change-transform active:scale-[0.98]';
  const variants = {
    primary: 'bg-[var(--swal-accent)] text-white hover:bg-[var(--swal-accent-hover)] shadow-sm',
    secondary: 'bg-[var(--swal-surface)] text-[var(--swal-text)] border border-[var(--swal-border)] hover:bg-[var(--swal-surface-hover)]',
    ghost: 'text-[var(--swal-text-secondary)] hover:bg-[var(--swal-surface-hover)]',
    danger: 'bg-[var(--swal-danger)] text-white hover:opacity-90',
  };
  const sizes = { sm: 'h-8 px-3 text-xs rounded-md', md: 'h-10 px-4 text-sm rounded-lg', lg: 'h-12 px-6 text-base rounded-lg' };
</script>

<button
  class="{base} {variants[variant]} {sizes[size]} {fullWidth ? 'w-full' : ''} {disabled || loading ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}"
  {disabled}
  on:click
  use:swalSlide={{ duration: 200 }}
>
  {#if loading}
    <span class="loading-spinner w-4 h-4 mr-2" />
  {/if}
  <slot />
</button>

<style>
  .loading-spinner {
    border: 2px solid transparent;
    border-top-color: currentColor;
    border-radius: 50%;
    animation: spin 0.6s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
</style>

// src/components/ui/Button.tsx
import * as React from 'react';
import { cn } from '../../utils/cn';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'outline' | 'ghost' | 'danger' | 'cyan';
  size?: 'default' | 'sm' | 'lg' | 'icon';
  glow?: boolean;
}

/**
 * SWAL Button — base del design system
 * Variantes: default (orange), outline, ghost, danger, cyan
 */
const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant = 'default', size = 'default', glow = false, ...props }, ref) => {
    const variants = {
      default:
        'bg-hive-orange text-slate-950 font-semibold hover:bg-hive-orange/90' +
        (glow ? ' shadow-neon-orange' : ''),
      outline:
        'border border-white/15 bg-transparent hover:bg-white/5 hover:text-white',
      ghost: 'bg-transparent hover:bg-white/5 hover:text-white',
      danger: 'bg-red-500 text-white hover:bg-red-500/90 shadow-neon-red',
      cyan: 'bg-hive-cyan text-slate-950 font-semibold hover:bg-hive-cyan/90' +
        (glow ? ' shadow-neon-cyan' : ''),
    };

    const sizes = {
      default: 'h-10 px-4 py-2 text-sm',
      sm: 'h-9 rounded-md px-3 text-xs',
      lg: 'h-11 rounded-md px-8 text-base',
      icon: 'h-10 w-10',
    };

    const base =
      'inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50';

    return (
      <button
        className={cn(base, variants[variant], sizes[size], className)}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = 'SwalButton';

export { Button };
