// src/components/StatusBadge.svelte
<script>
  // astro|island|client:visible|client:load
  // Portado de edge-hive-admin/components/StatusBadge.tsx
  let {
    status = 'offline', // 'healthy' | 'warning' | 'error' | 'offline'
    pulse = true,
  } = $props();
</script>

<span class="swal-status-badge" role="status" aria-label={status}>
  {#if pulse && status !== 'offline'}
    <span class="ring {status}" aria-hidden="true"></span>
  {/if}
  <span class="dot {status}" aria-hidden="true"></span>
</span>

<style>
  .swal-status-badge {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 12px;
    height: 12px;
  }
  .dot {
    position: relative;
    width: 8px;
    height: 8px;
    border-radius: 50%;
  }
  .ring {
    position: absolute;
    inset: 0;
    border-radius: 50%;
    opacity: 0.75;
    animation: swal-ping 1s cubic-bezier(0, 0, 0.2, 1) infinite;
  }
  .dot.healthy { background: #10b981; box-shadow: var(--swal-shadow-neon-cyan); }
  .ring.healthy { background: rgba(16, 185, 129, 0.2); }
  .dot.warning { background: var(--swal-accent-orange); box-shadow: var(--swal-shadow-neon-orange); }
  .ring.warning { background: rgba(249, 115, 22, 0.2); }
  .dot.error { background: #ef4444; box-shadow: 0 0 10px rgba(239, 68, 68, 0.5); }
  .ring.error { background: rgba(239, 68, 68, 0.2); }
  .dot.offline { background: #475569; }
  .ring.offline { background: rgba(71, 85, 105, 0.2); }

  @keyframes swal-ping {
    75%, 100% { transform: scale(2); opacity: 0; }
  }
  @media (prefers-reduced-motion: reduce) {
    .ring { animation: none; display: none; }
  }
</style>

// src/components/ui/StatusBadge.tsx
import * as React from 'react';
import { cn } from '../../utils/cn';

export type StatusType = 'healthy' | 'warning' | 'error' | 'offline';

export interface StatusBadgeProps {
  status: StatusType;
  pulse?: boolean;
  label?: string;
  size?: 'sm' | 'md';
}

const dotColors: Record<StatusType, string> = {
  healthy: 'bg-emerald-500 shadow-neon-cyan',
  warning: 'bg-hive-orange shadow-neon-orange',
  error: 'bg-red-500 shadow-neon-red',
  offline: 'bg-slate-600',
};

const ringColors: Record<StatusType, string> = {
  healthy: 'bg-emerald-500/20',
  warning: 'bg-orange-500/20',
  error: 'bg-red-500/20',
  offline: 'bg-slate-600/20',
};

const labelColors: Record<StatusType, string> = {
  healthy: 'text-emerald-400',
  warning: 'text-hive-orange',
  error: 'text-red-400',
  offline: 'text-slate-500',
};

/**
 * SWAL StatusBadge — indicador de estado con pulso neon
 */
export const StatusBadge: React.FC<StatusBadgeProps> = ({
  status,
  pulse = true,
  label,
  size = 'sm',
}) => {
  const dotSize = size === 'sm' ? 'h-2 w-2' : 'h-3 w-3';
  const containerSize = size === 'sm' ? 'w-3 h-3' : 'w-4 h-4';

  return (
    <div className="flex items-center gap-2">
      <div className={cn('relative flex items-center justify-center', containerSize)}>
        {pulse && (
          <span
            className={`absolute inline-flex h-full w-full rounded-full opacity-75 animate-ping ${ringColors[status]}`}
          />
        )}
        <span className={`relative inline-flex rounded-full ${dotSize} ${dotColors[status]}`} />
      </div>
      {label && <span className={`text-xs font-mono uppercase ${labelColors[status]}`}>{label}</span>}
    </div>
  );
};

export default StatusBadge;
